[project]
name = "tp-seleniumbase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pytest>=8.3.5",
    "requests>=2.32.3",
    "selenium>=4.32.0",
    "seleniumbase>=4.38.2",
]
